### ISSUE TITLE
Error on Custom Panel

### ISSUE THREAD

**Issue by e2m32** [gazoscalvertos/Hass-Custom-Alarm#10]
Hi @gazoscalvertos,

I started noticing this error I think after upgrading Hassio to 0.63, I'm on vr 0.64.3 now and just updated the Hass-Custom-Alarm to the most recent version. I am still getting this error. It doesn't seem to affect functionality, but it happens every time I load the panel:

`2018-03-09 23:29:44 ERROR (MainThread) [frontend.js.latest.201802270] https://myhomeassistant.duckdns.org:8123/frontend/panels/alarm-001f97509c39e788542bd2b51deb052d.html:448:86 Uncaught TypeError: Cannot read property 'state' of undefined`

Any ideas what this might be?

**Comment by gazoscalvertos** [comment]
Any other errors in the logs?

This appears to point to 

`this.temp = Math.ceil((this.hass.states['sensor.dark_sky_apparent_temperature']).state);`

**Comment by e2m32** [comment]
No. That's the only error...

I don't have that sensor though. SO that would make sense! I only have

`sensor.dark_sky_summary`

I'll add that sensor... that should do it.

**Comment by e2m32** [comment]
Ok! That seemed to fix that error 👍 and now I get the temperature :-) Thanks!

Unfortunately, now I am getting this error:
`2018-03-15 11:15:11 ERROR (MainThread) [frontend.js.latest.201803100] https://myhomeassistant.duckdns.org:8123/local/alarm/alarm_scripts.js:38:21 Uncaught TypeError: Cannot read property 'left' of null`

**Comment by gazoscalvertos** [comment]
Could you update to the latest code and retry I believe this is fixed.

**Comment by e2m32** [comment]
Hi @gazoscalvertos,

Thanks for the ping. Just updated. I still got an error, but then I added the java script version to my config and it all looks good now. 

You did a lot of updates to the alarm.yaml file. Looks good. Thanks again for all your work on this project! :-) 
 
`#CONFIGURATION.YAML
frontend:
  javascript_version: latest`

The new (i)nfo icon is really cool! I got these Issues:

```
ISSUES:
• Time Sensor (sensor.time) not found in HA

• Weather temperature entity not found in HA

• Time Sensor (sensor.time) not found in HA

• Time Sensor (sensor.time) not found in HA

• Weather temperature entity not found in HA

INFO:
HA: v0.70.1

THIS PANEL: v1.1.2

BWALARM: v1.0.2

PYTHON: v(3,6,3,final,0)
```

I'm going to dig a bit to see what sensors I need to install to resolve these.
