### ISSUE TITLE
Cannot read property 'left' of null

### ISSUE THREAD

**Issue by TheZoker** [gazoscalvertos/Hass-Custom-Alarm#11]
Since update to 0.65 I get this error in the console:
![screenshot_2018 03 11_17h42m16s_005_](https://user-images.githubusercontent.com/1368405/37255912-b06b0e8c-2553-11e8-9aed-74e545f5ba36.png)

**Comment by gazoscalvertos** [comment]
Ahh, I suspected a future update may break the hiding of the menu when armed. 

Leave it with me and I'll update, I'll try and place some error checking in too for future changes.

**Comment by gazoscalvertos** [comment]
Fixed
