### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jhefer123** [gazoscalvertos/Hass-Custom-Alarm#13]
Hi,

Would it be possible to do a similar python app where in home assistant where you input an image of an electricity meter and home assistant would calculate what your bill would be and email that image directly to the municipality and you would get an an notification to take an image every month?

Kind Regards,
Johan

**Comment by gazoscalvertos** [comment]
This isn't a feature that can be added to the alarm or security panel and is more a generic Home Assistant one. To be honest I think it would be quite difficult to write a python script to read the meter from a photo. Your probably better off either setting up a reminder within HA or installing a smart meter.
