### ISSUE TITLE
[CHECK] Persistence

### ISSUE THREAD

**Issue by gazoscalvertos** [gazoscalvertos/Hass-Custom-Alarm#19]

**Comment by BenchPressesBooks** [comment]
After testing persistence something is definitely broken here... it is re-applying the state of the alarm sensor once HASS reloads but for whatever reason none of the sensors will trigger the alarm.

Steps to reproduce:

1. Arm the system, doesn't matter what mode
2. Stop and start or restart home-assistant
3. Security system shows same state as it did before restarting
4. Trip any sensor, status change reflects on sensors page but alarm never goes off

Resolution: Still investigating. Temporary fix is to disarm and re-arm the security system and then everything works fine.

HASS: .82
HASS Alarm: Latest of NewUI bwalarm.py version 1.1.2
OS: Centos7 Minimal

**Comment by gazoscalvertos** [comment]
Could you re-try please. I believe this is now sorted in latest release. Thanks
