### ISSUE TITLE
Warning mode

### ISSUE THREAD

**Issue by overload08** [gazoscalvertos/Hass-Custom-Alarm#2]
Hey! That's an awsome project !

Just one question... Why when i have a delayed sensor trigger, open and close, warn mode doesn't disapear ?
alarm armed (black) -> sensor trigger (open) -> Warn mode (orange) -> sensor trigger (close) -> alarm mode (red)
I think that will be : 
alarm armed (black) -> sensor trigger (open) -> Warn mode (orange) -> sensor trigger (close) -> alarm armed (black)

Mostly for motion sensors if it detect presence for X seconds...

**Comment by gazoscalvertos** [comment]
The number of seconds determined to class as true motion should be defined in your motion device settings. i.e if its a zwave device the device itself will have a setting to determine when it should notify Home Assistant after X amount of seconds of motion.

Any motion detected and sent to HA and this custom alarm will always trigger the alarm or if its a delayed sensor it will give X amount of time before it allows you to disable the alarm without triggering it. For example 60 seconds to disable the alarm when you come through the front door and have triggered the front door open/close switch and the hallway motion detector.
