### ISSUE TITLE
[FIX] Panel lockout

### ISSUE THREAD

**Issue by gazoscalvertos** [gazoscalvertos/Hass-Custom-Alarm#21]

**Comment by BenchPressesBooks** [comment]
I am assuming this error is in reference to the UI comment stating the timeout needs to be fixed.. I have not been able to replicate the default behavior of "Defaults to 15 minutes. ###FIX THIS####" as the default is in seconds.

There is an issue though where the timeout is broken all together and causes the security panel to not load if the value is changed in the UI. This is a trivial fix though.

In custom_components/alarm_control_panel/bwalarm.py change the line
`CONF_PASSCODE_ATTEMPTS_TIMEOUT     = 'passcode_attempts_timeout'`
to 
`CONF_PASSCODE_ATTEMPTS_TIMEOUT     = 'passcode_attempt_timeout'`

It is writing the wrong variable and has nothing to read from if it is expecting to be able to read a value.

**Comment by gazoscalvertos** [comment]
Fixed in 1.3.6 alarm.html
