### ISSUE TITLE
MQTT Control Panel Support?

### ISSUE THREAD

**Issue by e2m32** [gazoscalvertos/Hass-Custom-Alarm#3]
Love this implementation! Thank you!

I am looking to use this with the MQTT Alarm Control panel app: https://play.google.com/store/apps/details?id=com.thanksmister.iot.mqtt.alarmpanel&hl=en

Is it possible to extend the functionality of this to include MQTT topics?

**Comment by gazoscalvertos** [comment]
Thanks!

That's a good idea, It will need a lot of re-work of the code but I'll add this to the list of items that I will incorporate. Will keep you posted.

**Comment by e2m32** [comment]
Awesome! Thanks @gazoscalvertos! Let me know if there is anything I can do to help. I'm going to try to come up with a work around for now.

**Comment by e2m32** [comment]
In case you're interested. This is the work around I came up with.

I defined a second alarm and set the code, pending_time, and trigger_time to the same values as the bwalarm:
```
- platform: manual_mqtt
  name: mqtt_handshake
  code: !secret ha_alarm_code
  pending_time: !secret ha_pending_time 
  trigger_time: !secret ha_trigger_time
  state_topic: home/alarm
  command_topic: home/alarm/set
  qos: 1
```

Then I set up an automation to sync the two alarm states:
```
- action:
  - data_template:
      code: !secret ha_alarm_code
      entity_id: >
        {% if trigger.entity_id == 'alarm_control_panel.mqtt_handshake' %}
          alarm_control_panel.house
        {% else %}
          alarm_control_panel.mqtt_handshake
        {% endif %}
    service_template: >
      {% if is_state(trigger.entity_id, 'disarmed') %}
        alarm_control_panel.alarm_disarm
      {% elif is_state(trigger.entity_id, 'armed_home') %}
        alarm_control_panel.alarm_arm_home
      {% elif is_state(trigger.entity_id, 'armed_away') %}
        alarm_control_panel.alarm_arm_away
      {% elif is_state(trigger.entity_id, 'armed_night') %}
        alarm_control_panel.alarm_arm_night
      {% else %}
        alarm_control_panel.alarm_arm_away
      {% endif %}
  alias: '[Alarm] HA to MQTT Sync'
  condition:
    condition: template
    value_template: >
      {% if states.alarm_control_panel.mqtt_handshake.state == states.alarm_control_panel.house.state %}
        false
      {% else %}
        true
      {% endif %}
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
  - entity_id: alarm_control_panel.mqtt_handshake
    platform: state
```

There might be a more elegant way of doing this, but it looks like it's working. Obviously, having native MQTT support in the 'bwalarm' would be awesome. I tried looking at your code and the MQTT Alarm Control Panel code, and yeah, it doesn't look like a simple update. I was thinking that when you change states you could also just publish the MQTT message and then also listen to MQTT messages to trigger state changes... but it doesn't look that simple at first glance. I'm pretty new to this platform and have about 0 experience with MQTT so there's that. I have a lot yet to learn about how to integrate with Home Assistant. 

Cheers.

**Comment by gazoscalvertos** [comment]
That's really useful thanks!

I do want to integrate it natively, hopefully I'll get some time this weekend to look at it. 

I'm considering restructuring the entire code to be honest as this was a fork from someone elses originally and there's a lot I'd like to change.

I'm also new to MQTT but have played with it previously and it doesn't seem to difficult to pull into this setup.

I'm just wondering what are the benefits of including MQTT? What extra features does the android app bring?

**Comment by e2m32** [comment]
Well with the MQTT alarm you can read and control alarm states via MQTT topics or messages. So in the case of the app, you can control the state and read the state of the alarm. This way the control panel is a really clean interface for a smaller screen (I'm using an old galaxy s3), and someone entering your house does not have access to the other features in HA. Just the alarm panel. There are other MQTT Alarm panels that folks have built that use real buttons or a similar interface running on a rPi zero.

Here's 2 other interfaces: 
https://www.hackster.io/colinodell/diy-alarm-control-panel-for-home-assistant-ac1813
https://community.home-assistant.io/t/diy-poor-mans-alarm-control-panel/23930/7

It also looks like this allows you to use some pre-existing control panels from other manufacturers:
https://community.home-assistant.io/t/home-assistant-and-paradox-alarm-panels/16042

You could also use anything that can send MQTT messages to arm or disarm or read the state of the alarm. So that just opens up a lot of possibilities.

**Comment by gazoscalvertos** [comment]
I have just updated the repo (bwalarm) with MQTT integration could you test?

**Comment by e2m32** [comment]
Wow! That was much faster than I expected! Sure thing. I'll hook it up tonight and see how it works.

**Comment by e2m32** [comment]
Hey @gazoscalvertos!

Looks like it's working. I'll keep running it to make sure it's stable.

It wasn't working. So I ganderd at your code and saw that I had to add this to my alarm.yaml config:
mqtt: True

Might want to call that out in the alarm.yaml config. Maybe:
mqtt: False   # allows for mqtt alarm control panel
# state_topic: home/alarm
# command_topic: home/alarm/set

**Comment by gazoscalvertos** [comment]
Thanks for the heads up. I thought I had uploaded the latest alarm.yaml. There are some extra options in there too.

I plan on extending the functionality of this as it has some limitations. For example you will notice that disarming via MQTT does not require the valid code and the MQTT is fully reliant on a secure MQTT configuration i.e. secure username/password and a matching digital certificate.

The reason for this is the android app you linked doesn't pass over the alarm code when entered to be validated (which is a shame) I may contact the dev or write my own Android/IOS app if I can find the time. The app only validates the code you setup with the app itself.

I'll add some extra functions so that other custom MQTT alarm panels can be used.

Let me know if you can think of anything extra you would like as part of this system and I'll do my best to include it.

Yeah bitcoin fees are insane, I have most wallets to be honest but to name a few:

Ripple: rwuMp76ht6dmGvipxwKr5ZE6VpF7ZKC7qs
Litecoin: LTUViN3QUESkQk3mG2hvTzhLRQPVAd269f
Ether: 0xCbeD2D2cf0434370c1ca126707009b876b736609
Bitcoin Cash: 1FKZiaFLEEwuB19nzEVVnq2pc8mME5tGw9

Anything you donate to this project will be much appreciated!!

**Comment by gazoscalvertos** [comment]
Contacted the dev https://community.home-assistant.io/t/mqtt-alarm-control-panel-for-raspberry-pi-and-android/26484/99?u=gazoscalvertos

**Comment by e2m32** [comment]
Yeah. I thought about the code issue as well. Seemed a little insecure to me too. I thought maybe it wasn't implemented because if your MQTT connection wasn't secure, someone could just subscribe to your messages and discover your code anyway. But if they haven't already done that, then they could just publish a disarm message. So it would probably be better to require the code in the message. 

If the user is using a public MQTT broker like cloudmqtt, even just bridged to a local broker, their alarm could get armed or disarmed remotely. A little scary, because you know that if enough users are setting this up that's going to happen. Which reminds me that I need to set up SSL.

Thanks for sharing your conversation with the dev. This is an exciting project. Using HA as an alarm is badass. Lightyears better than my crappy old Brinks alarm. Love that I can still use the old wired sensors with GPIO pins, and integrate any IOT device.

**Comment by gazoscalvertos** [comment]
Completely agree HA is awesome, the alarm element is why I got into it in the first place.

The possibilities are endless, especially when new technologies begin to appear.

Given your clued up on crypto image a smart contract on the blockchain which says that if your cleaner opened the door disarmed the alarm (using their assigned code) did their cleaning job (rearmed the alarm) (or even clocked in/out on the panel) then providing its within the agreed time etc xrp/eth/ltc would be transferred to their account automatically

**Comment by e2m32** [comment]
Totally endless. It's amazing how much you can do with a little Raspberry Pi. 

Yeah, or the cleaning lady could unlock with presence aware within the agreed upon time window and not need a code. That's how mine currently works... it just so happens that my 'cleaning lady' is my wife... and myself.

So when is the writing to the blockchain feature coming to the alarm panel? ;-)

Blockchain tech is so interesting. The possibilities of smart contracts and storing data on a blockchain are really endless. It's just a matter of finding use cases that make sense and implementing them well. There are some great gov't use cases... too bad it will be a millennia before gov't will do anything like that. I still have to mail in my tax forms with a check for my city taxes. And forget the medical industry. Having your medical information on a blockchain would be great. Then you could actually own your medical information, but the medical industry still depends on Fax Machines! to move around medical information. It's a joke. In their defense though, there is a lot of scaling and development that needs to occur before blockchain tech could be used at that scale. Just fun thinking about the possibilities.

**Comment by gazoscalvertos** [comment]
Ha probably a long way off that but I'm tempted to develop an address tracker component to monitor balances of currency (BTC, LTC, XRP, etc) addresses, Should be easy enough to do.

I actually work within the Health Service and totally agree, a patients medical record stored on the blockchain (encrypted for obvious reasons) accessible by the individual should/would improve the data quality and ultimately the healthcare that individual is provided with. I know there are trails here in the UK to make that happen.

Next big step, decentralized internet using the blockchain??

**Comment by e2m32** [comment]
I have actually done that for all of my coin. For most coins you can find a block explorer with an API and pull the JSON information. I just used Google Sheets to import everything. I also wrote a script to take hourly and daily snapshots so I can track the value of my portfolio. I thought about cleaning up a version of it that I could share, cause it's pretty slick. It's not perfect, sometimes Sheets times out on pulling an API and I get an error... then that messes up all of the calculations for that snapshot... but its still pretty good. If you want a copy of it, I'll do that. You can't track Monero though... it's totally encrypted. You can't see wallet balances. I was surprised to find that you can see wallet balances with Z-Cash, you just can't see where funds are sent and received. 

Oh man, yeah, the medical industry needs that so bad. The US is, I'm sure much further behind than the UK in that area... It would be awesome to own your encrypted data and if you change doctors or are traveling you can share your data with the doctor that is servicing you if needed. I've heard of blockchain start-ups that are working on it. Hope they can make it happen. I feel like it would be hard to get into the industry, but hopefully I am wrong. 

Decentralized internet would be great. There is a lot of centralization here as far as ISPs go... blockchain probably wouldn't help there. But as far as data, definitely. Google knows way too much about me. But I am so dependent on their services, that I have to give them all of my personal data (emails, location, files, text messages, voicemails, phone calls (I use Google Fi)). It's scary. I sure wish I owned that stuff. Have you looked into IPFS? That might be a good step in the right direction. Pretty cool tech. And if Filecoin pans out (is to be built on IPFS), there might be a way to incentivize people to host decentralized websites and data.

**Comment by gazoscalvertos** [comment]
Awesome, so is that feeding into HA?

I've got mine pulling into Kustom which is a custom Android live screensaver, everytime I unlock the phone it pulls the latest balance + current price in USD

All still very early days for blockchain tech, now is the time to get in if you can.

I'd never even heard of IPFS but it looks awesome! Thanks for the headsup.

**Comment by e2m32** [comment]
Woah man! You've been busy!! I've been getting an error since my update to 0.63 and came back to see if you have had any updates. Damn. Going to update to the latest version and see if I'm still getting it. Finally sent you some ETH about a week or so ago. Hope you got it. Cheers.

**Comment by gazoscalvertos** [comment]
Yeah thanks man! its very much appreciated! I thought it was you.

Going to put the donations towards some high end zigbee/zwave locks around the house.

Let me know if there's any extra features you want adding in.
