### ISSUE TITLE
[BUG] Dark Sky Unit of Measure ignored on Alarm Page Temperature Value

### ISSUE THREAD

**Issue by MwC-Trexx** [gazoscalvertos/Hass-Custom-Alarm#30]
Temperature value always displayed in C(celsius) regardless of Dark Sky unit setting to F (fahrenheit).

**Comment by pharpe** [comment]
It's hard coded into the panels\alarm.html.  

Look for this line
`<span>[[temp]] &#176;C</span>`
change to 
`<span>[[temp]] &#176;F</span>`

**Comment by gazoscalvertos** [comment]
I've added an option in the settings to display the temp in fahrenheit. See version 1.3.6 of alarm.html
