### ISSUE TITLE
NEW UI **BUG** "Home" and "Away" Disappear 

### ISSUE THREAD

**Issue by Crookedconverse** [gazoscalvertos/Hass-Custom-Alarm#35]
I had open sensors that were not selected to be overridden. When I attempted to arm the alarm, the "Home" and "Away" buttons disappeared and I had to reload the page to be able to set the alarm. 

**I'll attach my  alarm.yaml below:**
![alarm_panel_bug_yaml_file](https://user-images.githubusercontent.com/16129484/43609669-4611ae6e-966a-11e8-96e3-e003bb74597f.PNG)

**************************************************************************************************************************************************************************************************************************

platform: bwalarm
name: House
panel:
  cameras: []
  panel_title: Password is password
  enable_clock: true
  enable_clock_12hr: true
  enable_sensors_panel: true
states:
  armed_away:
    immediate: []
    delayed:
    - binary_sensor.motion_sensor_158d00023d8ac1
    - binary_sensor.door_window_sensor_158d00020b7bc1
    - binary_sensor.motion_sensor_158d000239866f
    - binary_sensor.motion_sensor_158d00023db67a
    - binary_sensor.door_window_sensor_158d00020b5564
    - binary_sensor.motion_sensor_158d00023972e0
    - binary_sensor.door_window_sensor_158d0002394353
    - binary_sensor.door_window_sensor_158d00023eb1a1
    - binary_sensor.door_window_sensor_158d000245b370
    - binary_sensor.motion_sensor_158d00023938eb
    - binary_sensor.door_window_sensor_158d00020b7c28
    - binary_sensor.door_window_sensor_158d000208e169
    override:
    - binary_sensor.motion_sensor_158d00023d8ac1
    - binary_sensor.motion_sensor_158d00023db67a
    - binary_sensor.motion_sensor_158d00023938eb
    pending_time: 0
    warning_time: 0
    trigger_time: 600
  armed_home:
    immediate: []
    delayed:
    - binary_sensor.motion_sensor_158d00023d8ac1
    - binary_sensor.door_window_sensor_158d00020b7bc1
    - binary_sensor.motion_sensor_158d000239866f
    - binary_sensor.motion_sensor_158d00023db67a
    - binary_sensor.motion_sensor_158d00023972e0
    - binary_sensor.door_window_sensor_158d00020b5564
    - binary_sensor.door_window_sensor_158d000208e169
    - binary_sensor.motion_sensor_158d00023938eb
    - binary_sensor.door_window_sensor_158d00020b7c28
    - binary_sensor.door_window_sensor_158d000245b370
    - binary_sensor.door_window_sensor_158d00023eb1a1
    - binary_sensor.door_window_sensor_158d0002394353
    override:
    - binary_sensor.motion_sensor_158d00023972e0
    - binary_sensor.motion_sensor_158d00023db67a
    - binary_sensor.motion_sensor_158d000239866f
    - binary_sensor.motion_sensor_158d00023d8ac1
    - binary_sensor.motion_sensor_158d00023938eb
    pending_time: 0
    warning_time: 0
    trigger_time: 600
  armed_perimeter:
    immediate: []
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: 600
code: '0000'
enable_persistence: true
admin_password: password
log: {}
code_to_arm: true

**BEFORE ARM HOME**
![alarm_panel_bug_prior_to_arm_home](https://user-images.githubusercontent.com/16129484/43609583-0c4afbb8-966a-11e8-97ed-6f0738c0c56c.PNG)

**AFTER ARM HOME**
![alarm_panel_bug](https://user-images.githubusercontent.com/16129484/43609519-de597842-9669-11e8-9ff1-6bb3d5bf0fff.PNG)

**Comment by gazoscalvertos** [comment]
Thanks for the update and for including the screenshots which are helpful!

I know whats causing this, its the open sensors notification which isn't working when you require a code to arm. I'll fix this now

**Comment by Crookedconverse** [comment]
You're welcome. I'm pretty excited about  your alarm panel. Thank you for making it.

**Comment by gazoscalvertos** [comment]
Resolved in 1.3.2
