### ISSUE TITLE
Custom interface broken in .79.3

### ISSUE THREAD

**Issue by adipose** [gazoscalvertos/Hass-Custom-Alarm#42]
When opening the alarm interface, I'm greeted with a hollow red circle and the whole interface crashes, requiring a browser reload of the page to do anything.  Clicking on the alarm interface again crashes it again.

The button from the overview page works as expected.

Version .79.3

**Comment by adipose** [comment]
I was able to fix it by changing my alarm id to lower case on both alarm.yaml and panel_custom.yaml.

**Comment by jbarcelov** [comment]
When I opening the alarm interface, I'm greeted with a hollow red circle and the whole interface crashes, 

Error was: 
alarm:462 Uncaught TypeError: Cannot read property 'attributes' of undefined
    at HTMLElement.updateTime (alarm:462)
    at Object.runMethodEffect [as fn] (app-084b7564.js:1067)
    at runEffectsForProperty (app-084b7564.js:1067)
    at runEffects (app-084b7564.js:1067)
    at HTMLElement._propertiesChanged (app-084b7564.js:1067)
    at HTMLElement._flushProperties (app-084b7564.js:1446)
    at HTMLElement._flushProperties (app-084b7564.js:1067)
    at HTMLElement.ready (app-084b7564.js:1067)
    at HTMLElement.ready (app-084b7564.js:1101)
    at HTMLElement.ready (alarm:270)

any ides????

Version .79.3

**Comment by adipose** [comment]
The problem was caused, for me, by it not being able to find the correct alarm id.  In my case, because even though my alarm was in caps, it had to be in lowercase in alarm.yaml.

**Comment by jbarcelov** [comment]
In my alarm:
##########################################################
platform: bwalarm
name: house

alarm: automation.alarm_triggered
warning: automation.alarm_warning
##########################################################

In my Panel_custom.yaml:
##########################################################
  - name: alarm
    sidebar_title: house
    sidebar_icon: mdi:security-home
    config:
      alarmid: alarm_control_panel.house ## USE THE SAME ID AS USED IN YOUR ALARM.YAML
##########################################################

I have everything in lowercase, but still does not work.

Any idea??

**Comment by adipose** [comment]
Perhaps the lowercase was not what fixed it.  Try using a totally different identifier like myhouse just to see if it fixes things. 

Did you do javascript:latest already?

**Comment by jbarcelov** [comment]
I have changed the name to myhouse in alarm.yaml and panel_custom.yaml, but it still does not work.

In configuration.yaml I have this:
##############################################################
# Enables the frontend
frontend:
  javascript_version: latest
##############################################################

The error is:

api/panel_custom/alarm:462:19 Uncaught TypeError: Cannot read property 'attributes' of undefined

**Comment by gazoscalvertos** [comment]
@jbarcelov It appears you are using the master release. Please use the NewUI branch and try again. I will merge the newui changes into the master release
