### ISSUE TITLE
Just updated HA to 0.80.0

### ISSUE THREAD

**Issue by MYLE-01** [gazoscalvertos/Hass-Custom-Alarm#46]
Just updated HA to 0.80.0

when I click AWAY MODE  

nothing happen now
log say this

![image](https://user-images.githubusercontent.com/4362345/46899520-eb4d8880-cef0-11e8-92fa-6739ddba748a.png)

**Comment by aidbish** [comment]
Getting the same issue after updating, had to revert back to 79.3
i posted in the forum about it and error i was getting.
 https://community.home-assistant.io/t/yet-another-take-on-an-alarm-system/32386/1172

**Comment by cdce8p** [comment]
@aidbish I replied in the HA forum to your post.

@MYLE-01 Can you please post the complete log from `.homeassistant/home-assistant.log`? Although check your pin code first. It at least says so in the screenshot you've provided.

**Comment by gazoscalvertos** [comment]
ok folks have identified the issue and believe I have a fix to resolve the defect caused by the withdrawal of the switch.turn_on. Will test and update tomorrow

**Comment by gazoscalvertos** [comment]
Issued a further fix this morning and have tested with automations which work. Could you also test please?

**Comment by pharpe** [comment]
So if the fix just the updated bwalarm.py file?  I copied over the new bwalarm.py but that is not working.  The check config hangs.  After restart the Alarm panel does not work at all.  Just get a small circle in the top left corner.

**Comment by pharpe** [comment]
So if the fix just the updated bwalarm.py file? I copied over the new bwalarm.py and the alarm is now fixed but my siren no longer works.
