### ISSUE TITLE
Keypad layout is different on smartphone

### ISSUE THREAD

**Issue by akasma74** [gazoscalvertos/Hass-Custom-Alarm#56]
The keypad's look on smartphone is different to it on desktop/tablet browsers because Clear and Disarm buttons are at the bottom and not at the right.
Is that intentional?

And there is no clock even though it is enabled and present on other platforms.

**Comment by lovejoy777** [comment]
clock & weather are there but phone needs to be in landscape to see them.

**Comment by akasma74** [comment]
I have only clock configured, but I cannot see it on my phone whatever the orientation
