### ISSUE TITLE
[MQTT] Warning Mode

### ISSUE THREAD

**Issue by TheCellMC** [gazoscalvertos/Hass-Custom-Alarm#6]
I set this component up to work the the MQTT control panel app. However, when the alarm goes to warning, the app does not update. I think the cause of this is that the app can only receive these payloads: disarmed, armed_away, armed_home, pending, triggered.
Can this bug be easily fixed on your side or should I contact the app's developer?

On another note, why can't I set the alarm to armed_home when it set to armed_away via a service call? I made some physical buttons to arm the alarm to home and away. However, sometimes I press the wrong button (ie, I arm the alarm to home instead of away). As a result, I have to disarm the alarm and then arm it away again.

**Comment by e2m32** [comment]
Hi @TheCellMC,

Yeah the app does not have a way to handle "Warning." What I did was use Tasker with MQTT Client (I'm using an old Android phone) and had the phone make a long loud beep when the Warning message is sent... you could also have it Say "Warning - XXX Sensor." There's not much @gazoscalvertos could do to help interface with the app in the warning situation. Like you said, the app doesn't have a function for that condition. You could modify the code and replace "warning" with triggered if you wanted... then the app would respond as if triggered was called. Or you could clone the app and code it to handle "Warning" if you know what your doing/want it to do.

In response to your other question. That's how the other alarm systems function as well. Probably as you should expect. Most of the time Home Mode means that the motion sensors are disabled. Imagine a bad guy came in your house while it was armed, and got to your alarm panel without getting caught by the motion sensor, he could just change it to Arm Home... walk around the house get everything ready to jet out the door and then just trigger it to get out without ever setting off the alarm. In all respect... just don't press the wrong button.

**Comment by Miadams** [comment]
Thank you
