### ISSUE TITLE
Error while setting up platform bwalarm: init_variables (KeyError: 'disarmed')

### ISSUE THREAD

**Issue by akasma74** [gazoscalvertos/Hass-Custom-Alarm#70]
**Describe the bug**
If there is alarm.json file in `/config` folder, alarm component does not start.
bwalarm.py v.1.1.4

**To Reproduce**
0. Make sure there is no `alarm.json` in your `/config` folder (rename/delete if needed)
1. Open alarm panel (by selecting Alarm from the main HA menu)
2. Arm and disarm alarm (that makes it save persistence information into `alarm.json`)
3. Restart HA (`hassio ha restart`)
4. Check error log `/config/hole-assistant.log`, you'll see

> ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform bwalarm
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
>     SLOW_SETUP_MAX_WAIT, loop=hass.loop)
>   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
>     res = func(*args, **kw)
>   File "/config/custom_components/alarm_control_panel/bwalarm.py", line 316, in async_setup_platform
>     alarm = BWAlarm(hass, config, mqtt)
>   File "/config/custom_components/alarm_control_panel/bwalarm.py", line 341, in __init__
>     self.init_variables()
>   File "/config/custom_components/alarm_control_panel/bwalarm.py", line 441, in init_variables
>     self.immediate  = self._states[self._state]["immediate"]
> KeyError: 'disarmed'
> 

**Expected behavior**
The alarm component should start as normal when HA restarted in Disarmed mode.
Please note that everything works as expected in Armed away/Home mode.

**Screenshots**
n/a

**Browser (please complete the following information):**
 any

**Additional context**
You can delete that alarm.json file and the alarm component will start properly.
However, it's only a workaround until the bug is fixed. 
A possible fix is [here](https://github.com/gazoscalvertos/Hass-Custom-Alarm/pull/72)

**Comment by RowdyDog12** [comment]
I can say that I also have this issue.

**Comment by WaaromZoMoeilijk** [comment]
Me 2


arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.2
version | 0.88.1
virtualenv | false

**Comment by djmcp** [comment]
Confirmed for me as well.  

Home Assistant: v0.88.2

**Comment by akasma74** [comment]
Yes, it's still there as the author is yet to review the [potential fix](url
https://github.com/gazoscalvertos/Hass-Custom-Alarm/pull/72).
However, there is nothing to stop you from fixing your local copy and enjoying it as I do ;)
