### ISSUE TITLE
[FEATURE REQ] Hide sensors when armed and disable home mode

### ISSUE THREAD

**Issue by TheZoker** [gazoscalvertos/Hass-Custom-Alarm#8]
Awesome work!

I just have one suggestion:
Show sensors when in disarmed mode, but hide it when it's in armed mode. 

Also, allow disabling the home mode (I just use the away mode).

That would be nice!

**Comment by gazoscalvertos** [comment]
No probs will drop it into a future release

**Comment by gazoscalvertos** [comment]
Added option within the settings to hide sensors when armed in version 1.3.6 of the alarm.html
